export const teclados = [
    {
        id: 1,
        nombre: "Ducky ONE",
        precio: "10000",
        categoria: '60',
        marca: 'Ducky',
        descripcion: "Teclado mecánico de la marca Ducky, wireless 60%, 60 teclas",
        img: "https://i.ibb.co/MMnvsvW/teclado1.jpg",
        stock: "15",
      },
      {
        id: 2,
        nombre: "Ducky G",
        precio: "20000",
        categoria: 'TKL',
        marca: 'Ducky',
        descripcion: "Teclado mecánico de la marca Ducky, cableado TKL, 70 teclas",
        img: "https://i.ibb.co/s507Kxs/teclado2.jpg",
        stock: "5",
      },
      {
        id: 3,
        nombre: "Signal WHITE",
        precio: "5000",
        categoria: '60',
        marca: 'Signal',
        descripcion: "Teclado mecánico de la marca Signal, wireless 60%, 60 teclas",
        img: "https://i.ibb.co/LztkL4c/teclado3.png",
        stock: "2",
      },
      {
        id: 4,
        nombre: "Redragon Trown",
        precio: "7500",
        categoria: 'Full',
        marca: 'Redragon',
        descripcion: "Teclado mecánico de la marca Redragon, cableado full-size",
        img: "https://i.ibb.co/FBwnrcN/teclado4.jpg",
        stock: "7",
      },
      {
        id: 5,
        nombre: "Ducky Dimanche",
        precio: "12000",
        categoria: "Full",
        marca: 'Ducky',
        descripcion: "Teclado mecánico de la marca Ducky, cableado full-size",
        img: "https://i.ibb.co/3FHVRGP/teclado5.jpg",
        stock: "9",
      },
      {
        id: 6,
        nombre: "Redragon Kiros",
        precio: "8300",
        categoria: 'Full',
        marca: 'Redragon',
        descripcion: "Teclado mecánico de la marca Redragon, cableado full-size",
        img: "https://i.ibb.co/18sW77Q/teclado6.png",
        stock: "20",
      },
]

